name: go_router_example
description: go_router_example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.1.beta <3.0.0'
  flutter: '>=3.6.0-0.1.pre'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.7.0
  intl: ^0.17.0
  l: ^3.2.0
  go_router: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.0.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/localization
  output_dir: lib/src/common/localization/generated
  use_deferred_loading: false

flutter_gen:
  output: lib/src/common/constant/
  line_length: 120
